config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  get '/not_found', to: redirect('/404')


  root :to => 'sessions#new'
  resources :users
  resources :ideas, only: [:create, :edit, :new, :destroy, :update]
  scope module: 'admin' do
    resources :categories,  only: [:create, :index, :new, :destroy]
    post '/new', to: 'category#new'
    resources :images, only: [:index, :create, :edit, :new, :destroy, :update]

  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :ideas
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :category
  has_many :idea_images
  has_many :images, through: :idea_images
  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/idea_image.rb
class IdeaImage < ActiveRecord::Base
  belongs_to :idea
  belongs_to :image
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_many :idea_images
  has_many :ideas, through: :idea_images
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :ideas

  enum role: ["default", "admin"]


end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < ApplicationController
    before_filter :authorize, only: [:index, :destroy, :new, :create]

    def index
      if current_user.nil? || !current_user.admin?
        redirect_to not_found_path
      end
      @categories = Category.all
    end

    def destroy
    #  require 'pry', binding.pry
      # puts "this is id #{id}"

      Category.find(params[:id]).destroy
      flash[:message] = "Category deleted"
      redirect_to categories_path
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)

      respond_to do |format|
        if @category.save
          format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        else
         format.html { render :new }
        end
      end
    #  redirect_to categories_path
    end

    private

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/admin/images_controller.rb
module Admin
  class ImagesController < ApplicationController
    before_filter :authorize, only: [:index, :destroy, :new, :create]

    def index
      if current_user.nil? || !current_user.admin?
        redirect_to not_found_path
      end
      @images = Image.all
    end

    def destroy
    #  require 'pry', binding.pry
      # puts "this is id #{id}"

      Image.find(params[:id]).destroy
      flash[:message] = "Image deleted"
      redirect_to images_path
    end

    def new
      @image = Image.new
    end

    def create
      @image = Image.new(image_params)

      respond_to do |format|
        if @image.save
          format.html { redirect_to images_path, notice: 'Image saved.' }
        else
         format.html { render :new }
        end
      end
    #  redirect_to categories_path
    end

    private

    def image_params
      params.require(:image).permit(:link)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    #require 'pry'; binding.pry
    redirect_to not_found_path if current_user.nil?
   #raise ActionController::RoutingError.new('Not Found') if current_user.nil?
  #  render status: 404 if current_user.nil?
    # render :status => 404 if current_user.nil?
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authorize, only: [:create, :edit, :update, :destroy]
  before_filter :set_idea, only: [ :edit, :update, :destroy]

  def new
    @idea = Idea.new(user_id: params[:id])
    2.times { @idea.images.build}
  end

  def create
    @idea = Idea.create(idea_params)
    # require 'pry'; binding.pry
    params[:idea][:images].each do |image_id|
      @idea.idea_images.create(image_id: image_id.to_i ) unless image_id == ""
    end
    redirect_to user_path(@idea.user_id)
  end

  def destroy
    user_id = @idea.user_id
    @idea.destroy
    flash[:message] = "Idea deleted"
    redirect_to user_path(user_id)
  end

  def edit
    if current_user.id != @idea.user_id
      redirect_to not_found_path
    end
  end


  def update
    @idea.update(idea_params)
    redirect_to user_path(@idea.user_id), notice: 'Idea was successfully updated.'
  end

  private

  def idea_params
    params.require(:idea).permit(:name, :user_id, :category_id, images_attributes: [:id, :link])
    #  require 'pry'; binding.pry
  end


  def set_idea
    @idea = Idea.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:messages] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash[:errors] = "Invalid credentials"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:messages] = "You have successfully logged out"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:show]

  def show
    @user = User.find(params[:id])
    if @user != current_user && !current_user.admin?
      redirect_to not_found_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/index.html.erb
<div id="idea_categories">
  <h2>Current Categories:</h2>
  <tbody>
    <% @categories.each do |category| %>
    <%= content_tag :div, category.name, id:"category_#{category.name}" %>
    <%= category.id %>
    <%= link_to 'Delete',  category,  id:"delete_cat_#{category.id}",  method: :delete, data: { confirm: 'Are you sure?' }  %>

    <% end %>

  <p id="new_category"><%= link_to 'Add Category', new_category_path %></p>
</div>

app/views/admin/categories/new.html.erb
<%= form_for(@category) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Create category" %>
  </div>
<% end %>

app/views/admin/images/index.html.erb
<div id="images">
  <h2>Current Images:</h2>
  <tbody>
    <% @images.each do |image| %>
    <%= content_tag :div, image.link, id:"image_#{image.link}" %>
    <%= image.id %>
    <%= link_to 'Delete',  image,  id:"delete_#{image.id}",  method: :delete, data: { confirm: 'Are you sure?' }  %>

    <% end %>

    <p id="new_image"><%= link_to 'Add Image', new_image_path %></p>
  </div>

app/views/admin/images/new.html.erb
<%= form_for(@image) do |f| %>
<div class="field">
  <%= f.label :link %>
  <%= f.text_field :link %>
</div>
<div class="actions">
  <%= f.submit "Save image info" %>
</div>
<% end %>

app/views/ideas/edit.html.erb
<%= form_for(@idea) do |f| %>
<div class="field">
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="field">
  Images:
</br>
  <%= f.fields_for :images do |images_form| %>
    <%= images_form.label "Delete link" %>
    <%= images_form.check_box :_destroy %>
    <%= images_form.label "Image Link" %>
    <%= images_form.text_field :link %>

  <% end %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/ideas/new.html.erb
<%= form_for(@idea) do |f| %>
<div class="field">
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>


<%= f.select(:images, Image.all.collect { |i| [ i.link, i.id]}, {},{:multiple => true}) %>

<div class="field">
  <%= f.label :categories %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuthPracticeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<div id="ideas">
  <h2>Your Ideas:</h2>
  <ul>
    <% @user.ideas.each do |idea| %>
    <li><%= idea.name %>
      <% if !idea.category.nil? %>
        <%= idea.category.name %>
        <% idea.images.each do |image| %>
          <%= image.link %>
        <% end %>
      <% end %>
      <%= link_to 'Edit', edit_idea_path(idea) %>
      <%= link_to 'Delete', idea, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
    <% end %>
  </ul>

  <%= link_to "Add Idea", new_idea_path %></br>
  <% if current_user.admin? %>
    <%= link_to "Manage categories", categories_path %></br>
    <%= link_to "Manage images", images_path %></br>
  <% end %>

  <%= link_to "Logout", logout_path, method: 'DELETE' %>

</div>